import './style.css';
const app = document.querySelector('#app');
const $ = (s) => document.querySelector(s);
const presets = [['classic','Классика','✛'],['dot','Точка','•'],['circle','Кольцо','◎'],['cross','Крест X','×'],['plus','Плюс','＋'],['square','Квадрат','□'],['corners','Углы','⌜'],['chevron','Шеврон','∨']];
const defaults = { visible:true, shape:'classic', color:'#b8ff42', size:30, length:30, thickness:3, gap:7, opacity:100, offsetX:0, offsetY:0, dot:false, outline:true };
let cfg = {...defaults};
let shortcuts = {toggle:'Control+Alt+X', hide:'Control+Alt+H', larger:'Control+Alt+Up', smaller:'Control+Alt+Down'};
let page = 'crosshair';
document.body.classList.add('crosshair-page');
const colors = ['#b8ff42','#ffffff','#ff5470','#39c6ff','#bd83ff','#ffb547'];
app.innerHTML = `<aside class="sidebar"><div class="brand"><div class="logo">a<span>+</span></div><div><strong>aimxity</strong><small>OVERLAY STUDIO</small></div></div><div class="nav-label">РАБОЧЕЕ ПРОСТРАНСТВО</div><button class="nav-item active" data-page="crosshair"><span>◉</span> Прицел <b>01</b></button><button class="nav-item" data-page="hotkeys"><span>⌘</span> Горячие клавиши</button><button class="nav-item" data-page="profiles"><span>▤</span> Профили</button><div class="side-bottom"><div class="status"><i></i><div><strong>Оверлей активен</strong><small id="status-text">Готов к игре</small></div><span class="pulse"></span></div><div class="version">AIMXITY <span>v1.1.0</span></div></div></aside><main><header><div><div class="eyebrow">AIMXITY / <span id="crumb">КОНСТРУКТОР ПРИЦЕЛА</span></div><h1 id="page-title">Твой прицел<span>.</span></h1><p id="page-subtitle">Настрой точность под свой стиль игры.</p></div><button class="minimize" id="minimize" title="Свернуть">−</button></header>
<section id="view-crosshair" class="view active"><div class="layout"><section class="editor"><div class="card"><div class="section-head"><div><h2>Форма прицела</h2><p>Выбери тип и меняй любые параметры</p></div><span class="step">01</span></div><div class="shapes">${presets.map(([id,label,icon])=>`<button class="shape-choice ${id===cfg.shape?'selected':''}" data-shape="${id}"><span class="shape-icon">${icon}</span><span>${label}</span></button>`).join('')}</div><div class="divider"></div><div class="control-title"><h3>Цвет</h3><span class="hex" id="hex">${cfg.color.toUpperCase()}</span></div><div class="colors">${colors.map(c=>`<button class="swatch ${c===cfg.color?'picked':''}" style="--swatch:${c}" data-color="${c}" aria-label="${c}"></button>`).join('')}<label class="custom-color" title="Свой цвет">＋<input type="color" id="colorpicker" value="${cfg.color}"></label></div><div class="divider"></div><div class="control-title"><h3>Точные параметры <span class="unlimited">БЕЗ ОГРАНИЧЕНИЙ</span></h3></div><div class="number-grid">${[['size','Размер (px)'],['length','Длина линий (px)'],['thickness','Толщина (px)'],['gap','Зазор (px)'],['offsetX','Смещение X (px)'],['offsetY','Смещение Y (px)'],['opacity','Непрозрачность (%)']].map(([key,label])=>`<label class="number-field"><span>${label}</span><div class="dual-input"><input type="range" data-range="${key}" value="${cfg[key]}"><input type="number" step="any" data-number="${key}" value="${cfg[key]}"></div></label>`).join('')}</div><div class="toggles"><label><span><b>Центральная точка</b><small>Добавить точку в центр</small></span><input type="checkbox" id="dot"><i></i></label><label><span><b>Обводка</b><small>Контрастный контур прицела</small></span><input type="checkbox" id="outline" checked><i></i></label></div></div></section><section class="preview-column"><div class="preview-card"><div class="preview-top"><div><span class="live-dot"></span> ПРЕДПРОСМОТР</div><button id="reset" class="reset">↺ Сбросить</button></div><div class="game-preview"><div class="grid"></div><div class="scene"><div class="mountain back"></div><div class="mountain front"></div><div class="horizon"></div><div class="target"><i></i></div></div><div class="demo-crosshair" id="demo"></div><div class="preview-bottom"><span>TRAINING RANGE</span><span>1920 × 1080</span></div></div><div class="preview-footer"><span><i class="keycap">CTRL</i> + <i class="keycap">ALT</i> + <i class="keycap">X</i> показать / скрыть</span><span class="synced">● Синхронизировано</span></div></div><div class="quick-card"><div class="quick-icon">⌨</div><div class="quick-copy"><h3>Прицел по центру не совпадает?</h3><p>Используй смещение X и Y. Значения можно вводить вручную.</p></div></div><button class="launch" id="launch"><span>◉</span> Прицел включён <i>✓</i></button><p class="footnote">Некоторые игры и античиты могут блокировать сторонние оверлеи.</p></section></div></section>
<section id="view-hotkeys" class="view"><div class="card management"><div class="section-head"><div><h2>Горячие клавиши</h2><p>Нажми «Назначить», затем нужную комбинацию на клавиатуре.</p></div></div><div id="shortcut-list" class="shortcut-list"></div><p class="hint">Сочетание должно содержать Ctrl, Alt или Shift. Комбинации могут конфликтовать с игрой или Windows.</p></div></section>
<section id="view-profiles" class="view"><div class="card management"><div class="section-head"><div><h2>Профили прицела</h2><p>Сохраняй отдельные настройки для разных игр.</p></div></div><form id="profile-form" class="profile-form"><input id="profile-name" placeholder="Например, Valorant" maxlength="32" required><button class="launch compact" type="submit">＋ Сохранить текущий прицел</button></form><div id="profiles-list" class="profiles-list"></div></div></section></main>`;
function send(){window.aimxity?.update(cfg);renderPreview();}
function renderPreview(){const d=$('#demo');if(!d)return;const scale=Number(cfg.size)/30;const len=Number(cfg.length)*scale,t=Number(cfg.thickness)*scale,g=Number(cfg.gap)*scale;d.className=`demo-crosshair demo-${cfg.shape} ${cfg.outline?'outlined':''}`;for(const [key,val] of Object.entries({c:cfg.color,s:`${cfg.size}px`,len:`${len}px`,t:`${t}px`,g:`${g}px`,a:Math.max(0,Math.min(100,cfg.opacity))/100,'offset-x':`${cfg.offsetX}px`,'offset-y':`${cfg.offsetY}px`}))d.style.setProperty(`--${key}`,val);const center=cfg.dot?'<i class="center-dot"></i>':'';const markup={dot:'<i class="center-dot"></i>',circle:`<i class="ring"></i>${center}`,cross:`<i class="diagonal d1"></i><i class="diagonal d2"></i>${center}`,plus:'<i class="solid-h"></i><i class="solid-v"></i>',square:'<i class="square"></i>',corners:['tl-h','tl-v','tr-h','tr-v','bl-h','bl-v','br-h','br-v'].map(x=>`<i class="corner ${x}"></i>`).join(''),chevron:'<i class="chevron left"></i><i class="chevron right"></i>'};d.innerHTML=cfg.shape==='classic'?`<i class="arm a-top"></i><i class="arm a-bottom"></i><i class="arm a-left"></i><i class="arm a-right"></i>${center}`:(markup[cfg.shape]||markup.cross);}
function set(key,value){cfg[key]=value;send();}
document.querySelectorAll('[data-shape]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-shape]').forEach(x=>x.classList.toggle('selected',x===b));set('shape',b.dataset.shape)});
document.querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>chooseColor(b.dataset.color));function chooseColor(c){$('#hex').textContent=c.toUpperCase();$('#colorpicker').value=c;document.querySelectorAll('.swatch').forEach(s=>s.classList.toggle('picked',s.dataset.color===c));set('color',c)}
$('#colorpicker').oninput=e=>chooseColor(e.target.value);
function updateRangeBounds(key,value){const range=$(`[data-range="${key}"]`);if(!range)return;const max=Math.max(100,Math.ceil(Math.abs(value)*1.25));if(key==='offsetX'||key==='offsetY'){range.min=-max;range.max=max;}else{range.min=0;range.max=key==='opacity'?100:max;}range.value=value;}
function setNumeric(key,raw,fromSlider=false){if(raw===''||!Number.isFinite(Number(raw)))return;let value=Number(raw);if(key==='opacity')value=Math.max(0,Math.min(100,value));if(['size','length','thickness','gap'].includes(key))value=Math.max(0,value);cfg[key]=value;const number=$(`[data-number="${key}"]`);const range=$(`[data-range="${key}"]`);if(number&&fromSlider)number.value=value;if(range){updateRangeBounds(key,value);if(fromSlider&&(Number(range.value)===Number(range.max)||Number(range.value)===Number(range.min))){const expanded=Math.max(100,Math.ceil(Math.abs(value)*2));if(key==='offsetX'||key==='offsetY'){range.min=-expanded;range.max=expanded;}else if(key!=='opacity')range.max=expanded;range.value=value;}}send();}
document.querySelectorAll('[data-number]').forEach(input=>{const key=input.dataset.number;input.oninput=()=>setNumeric(key,input.value);updateRangeBounds(key,cfg[key])});document.querySelectorAll('[data-range]').forEach(range=>{const key=range.dataset.range;range.oninput=()=>setNumeric(key,range.value,true)});
$('#dot').onchange=e=>set('dot',e.target.checked);$('#outline').onchange=e=>set('outline',e.target.checked);
function setVisible(v){cfg.visible=v;window.aimxity?.update(cfg);$('#launch').classList.toggle('off',!v);$('#launch').innerHTML=v?'<span>◉</span> Прицел включён <i>✓</i>':'<span>◯</span> Прицел выключен <i>↗</i>';}
$('#launch').onclick=()=>setVisible(!cfg.visible);$('#reset').onclick=()=>{cfg={...defaults};send();document.querySelectorAll('[data-number]').forEach(i=>i.value=cfg[i.dataset.number]);$('#dot').checked=false;$('#outline').checked=true;chooseColor(cfg.color);document.querySelectorAll('[data-shape]').forEach(b=>b.classList.toggle('selected',b.dataset.shape===cfg.shape));};$('#minimize').onclick=()=>window.aimxity?.minimize();
const pageMeta={crosshair:['Твой прицел','КОНСТРУКТОР ПРИЦЕЛА','Настрой точность под свой стиль игры.'],hotkeys:['Управление','ГОРЯЧИЕ КЛАВИШИ','Настрой удобные сочетания клавиш.'],profiles:['Твои профили','ПРОФИЛИ ПРИЦЕЛА','Разные прицелы для разных игр.']};
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;document.body.classList.toggle('crosshair-page',page==='crosshair');document.querySelectorAll('[data-page]').forEach(n=>n.classList.toggle('active',n===b));document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${page}`));$('#page-title').innerHTML=pageMeta[page][0]+'<span>.</span>';$('#crumb').textContent=pageMeta[page][1];$('#page-subtitle').textContent=pageMeta[page][2];if(page==='profiles')renderProfiles();if(page==='hotkeys')renderKeys()});
function getProfiles(){try{return JSON.parse(localStorage.getItem('aimxity-profiles')||'[]')}catch{return []}}
function renderProfiles(){const list=$('#profiles-list');const profiles=getProfiles();list.innerHTML=profiles.length?profiles.map((p,i)=>`<article class="profile-row"><div class="profile-mark">✛</div><div class="profile-info"><b>${escapeHtml(p.name)}</b><small>${p.shape} · ${p.color} · размер ${p.size}px</small></div><button class="profile-load" data-load="${i}">Применить</button><button class="profile-delete" data-delete="${i}" title="Удалить">×</button></article>`).join(''):'<div class="empty-state">Профилей пока нет. Сохрани текущую настройку выше.</div>';list.querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>{cfg={...defaults,...profiles[+b.dataset.load].config};syncControls();send();document.querySelector('[data-page="crosshair"]').click()});list.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{const ps=getProfiles();ps.splice(+b.dataset.delete,1);localStorage.setItem('aimxity-profiles',JSON.stringify(ps));renderProfiles()})}
function escapeHtml(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML}
function syncControls(){document.querySelectorAll('[data-number]').forEach(i=>i.value=cfg[i.dataset.number]??0);document.querySelectorAll('[data-range]').forEach(i=>updateRangeBounds(i.dataset.range,cfg[i.dataset.range]??0));$('#dot').checked=cfg.dot;$('#outline').checked=cfg.outline;$('#hex').textContent=cfg.color.toUpperCase();$('#colorpicker').value=cfg.color;document.querySelectorAll('[data-color]').forEach(s=>s.classList.toggle('picked',s.dataset.color===cfg.color));document.querySelectorAll('[data-shape]').forEach(b=>b.classList.toggle('selected',b.dataset.shape===cfg.shape));setVisible(cfg.visible)}
$('#profile-form').onsubmit=e=>{e.preventDefault();const name=$('#profile-name').value.trim();if(!name)return;const ps=getProfiles();ps.push({name,config:{...cfg}});localStorage.setItem('aimxity-profiles',JSON.stringify(ps));$('#profile-name').value='';renderProfiles()};
function renderKeys(){const list=$('#shortcut-list');const titles={toggle:'Показать / скрыть прицел',hide:'Скрыть прицел',larger:'Увеличить размер',smaller:'Уменьшить размер'};list.innerHTML=Object.entries(shortcuts).map(([id,key])=>`<div class="shortcut-row"><span>${titles[id]}</span><kbd>${key.replaceAll('Control','CTRL').replaceAll('Alt','ALT').replaceAll('Shift','SHIFT').replaceAll('Up','↑').replaceAll('Down','↓')}</kbd><button data-bind="${id}">Назначить</button></div>`).join('');list.querySelectorAll('[data-bind]').forEach(b=>b.onclick=()=>{b.textContent='Нажми комбинацию…';b.classList.add('listening');const handler=e=>{e.preventDefault();if(!e.ctrlKey&&!e.altKey&&!e.shiftKey){b.textContent='Нужен Ctrl, Alt или Shift';return}const parts=[];if(e.ctrlKey)parts.push('Control');if(e.altKey)parts.push('Alt');if(e.shiftKey)parts.push('Shift');const key=e.key.length===1?e.key.toUpperCase():({ArrowUp:'Up',ArrowDown:'Down',ArrowLeft:'Left',ArrowRight:'Right', ' ':'Space'}[e.key]||e.key);if(['Control','Alt','Shift'].includes(key))return;parts.push(key);const accelerator=parts.join('+');shortcuts[b.dataset.bind]=accelerator;window.aimxity?.setShortcuts(shortcuts).then(result=>{if(result?.ok){localStorage.setItem('aimxity-shortcuts',JSON.stringify(shortcuts));renderKeys()}else{b.textContent='Комбинация занята';setTimeout(renderKeys,1200)}});window.removeEventListener('keydown',handler,true)};window.addEventListener('keydown',handler,true)})}
window.aimxity?.onState(setVisible);
window.aimxity?.get().then(data=>{if(data?.config){cfg={...defaults,...data.config};syncControls()}if(data?.shortcuts){shortcuts=data.shortcuts;localStorage.setItem('aimxity-shortcuts',JSON.stringify(shortcuts))}renderPreview()});
const savedShortcuts=localStorage.getItem('aimxity-shortcuts');if(savedShortcuts)try{shortcuts={...shortcuts,...JSON.parse(savedShortcuts)}}catch{}
renderPreview();
